### ISSUE TITLE
Is there any way to tell if it successfully posted?

### ISSUE THREAD

**Issue by bbarton** [jb3/webhook-discord#63]
How can we see if `Hook.send` actually posted? Is that even possible, or does the actual POST to discord not return a status?

When passing a callback to `Hook.send`, it just seems to return `undefined` no matter what.

**Comment by jb3** [comment]
Hook.send *should* be returning a promise?

**Comment by jb3** [comment]
https://github.com/jb3/webhook-discord/blob/21e0c38cf0e06e91f05c81ca3da35a9008f1a467/lib/webhook.js#L305

**Comment by bbarton** [comment]
It does, but the promise doesn't appear to resolve. For example, this posts to Discord, but nothing is printed to the console:

      Hook.send(msg)
        .then(response => console.log(`Discord message sent. Response: ${response}`))
        .catch(err => console.log(err));

Any idea what I'm doing wrong?

**Comment by jb3** [comment]
Hmmm, you are correct. How peculiar! I'll investigate!

**Comment by jb3** [comment]
Well, cracked it! It was just not passing the resolve payload if the webhook was not yet ready (the library validates webhook URLs before trying to send to them).

This is fixed in webhook-discord@3.7.7.

Thank you for reporting!
