### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by webbuildlucas** [jb3/webhook-discord#64]
I want to see the documentation to explore more of this, but when I click on the website github gives a 404 error. Can the documenation be placed in a file in this repo or on a working site?

**Comment by jb3** [comment]
Seems like I didn't update a link when I changed GitHub names!

Docs are at https://jb3.github.io/webhook-discord

I'll update those links now

**Comment by jb3** [comment]
Fixed and published with a security update in webhook-discord@3.7.6

Thanks!
