### ISSUE TITLE
embed url into title

### ISSUE THREAD

**Issue by chrispalka** [jb3/webhook-discord#66]
Not really an issue, but was wondering if there was a way to embed url into a title.

Similar to how discord api documents it below:

{
  "embeds": [{
    "title": "Google it!",
    "url": "https://google.com/"
  }]
}

**Comment by jb3** [comment]
Yep! Check out the [`setURL`](https://jb3.github.io/webhook-discord/MessageBuilder.html#setURL) method of the message builder.

Please feel free to re-open if you have any further questions.
